//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicPhotoGallary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.MainImages = new HashSet<MainImage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phoneno { get; set; }
        public string Attach { get; set; }
        public string Size { get; set; }
        public string Pack { get; set; }
        public string Message { get; set; }
    
        public virtual ICollection<MainImage> MainImages { get; set; }
    }
}
