//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicPhotoGallary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubImage
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int MainImageId { get; set; }
    
        public virtual MainImage MainImage { get; set; }
    }
}
